# Generated by Django 4.2.7 on 2024-06-17 18:44

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingaddress_email_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_order',
            field=models.CharField(default=orders.models.generate_num_order, max_length=15, unique=True),
        ),
    ]
