# Generated by Django 4.2.7 on 2024-06-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='city_state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
