# Generated by Django 4.2.7 on 2024-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('modelo', 'modelo'), ('capacidad', 'capacidad'), ('color', 'color')], max_length=100),
        ),
    ]
