# Generated by Django 4.2.7 on 2024-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
