# Generated by Django 4.2.7 on 2024-05-03 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_slug_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
