# Generated by Django 4.2.7 on 2024-05-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'name')},
        ),
    ]
