# Generated by Django 4.2.7 on 2024-05-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('capacidad', 'capacidad'), ('modelo', 'modelo'), ('color', 'color')], max_length=100, null=True),
        ),
    ]
