# Generated by Django 4.2.7 on 2024-05-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('capacidad', 'capacidad'), ('color', 'color'), ('modelo', 'modelo')], max_length=100, null=True),
        ),
    ]
