# Generated by Django 4.2.7 on 2024-05-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('modelo', 'modelo'), ('capacidad', 'capacidad')], max_length=100, null=True),
        ),
    ]
