# Generated by Django 4.2.7 on 2024-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product',
            new_name='id_product',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('modelo', 'modelo'), ('capacidad', 'capacidad'), ('color', 'color')], max_length=100, null=True),
        ),
    ]
