# Generated by Django 4.2.7 on 2024-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_product_variation_id_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('capacidad', 'capacidad'), ('modelo', 'modelo'), ('color', 'color')], max_length=100, null=True),
        ),
    ]
