# Generated by Django 4.2.7 on 2024-05-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product'),
        ),
    ]
