# Generated by Django 4.2.7 on 2024-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_variation_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
    ]
