# Generated by Django 4.2.7 on 2024-05-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
