# Generated by Django 4.2.7 on 2024-05-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_image_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
